#project-name
server:
  servlet:
    context-path: /sharon
  port: 9080

spring:
  datasource:
    sharon:
      url: jdbc:mysql://127.0.0.1:3306/sharon?allowMultiQueries=true
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: root
#      password: liangxin
      validation-query: SELECT 1;
      sql-script-encoding: UTF-8
      initial-size: 1
      max-active: 50
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      remove-abandoned-timeout: 5000
      max-pool-prepared-statement-per-connection-size: 300
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

    pms:
      url: jdbc:mariadb://192.168.3.86:3306/pms?allowMultiQueries=true
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: org.mariadb.jdbc.Driver
      username: sunny
      password: 6345463asd
      validation-query: SELECT 1;
      sql-script-encoding: UTF-8
      initial-size: 1
      max-active: 50
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      remove-abandoned-timeout: 5000
      max-pool-prepared-statement-per-connection-size: 300
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
  sleuth:
    sampler:
      probability: 1.0
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 7200
  mail:
    host: smtp.163.com
    username: lx_4509@163.com
    password: Aweiyue182520
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          connectiontimeout: 6000
          timeout: 3000
          writetimeout: 6000
  rabbitmq:
    addresses: 127.0.0.1:5672

sharon:
  uploadPath: C:\\home\\sharon\\